timezone: Australia/Melbourne

permalink: /:title

collections:
  posts:
    output: true
    permalink: /blog/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SCSS
sass:
  style: compressed

# SEO
title: Gavin Douch
tagline: Portfolio
description: Independent developer based in Melbourne
author:
  twitter: GavinDouch
twitter:
  username: GavinDouch
  card: summary
logo: /assets/images/siteIcons/apple-touch/apple-icon.png
social:
  name: Gavin Douch
  links:
    - https://twitter.com/GavinDouch
    - https://www.linkedin.com/in/gavin-douch-a77259117/
    - https://github.com/Coedice
    - https://gavindou.ch
locale: en-AU