timezone: Australia/Melbourne

permalink: /:title

collections:
  posts:
    output: true
    permalink: /blog/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# SCSS
sass:
  style: compressed

# SEO
title: Gavin Douch
tagline: Portfolio
description: I am an independent software developer and tech blogger from Melbourne, Australia.
author:
  twitter: GavinDouch
twitter:
  username: GavinDouch
  card: summary
logo: /assets/images/favicons/favicon-310.png
social:
  name: Gavin Douch
  links:
    - https://twitter.com/GavinDouch
    - https://www.linkedin.com/in/gavin-douch-a77259117/
    - https://github.com/Coedice
    - https://gavindou.ch
locale: en-AU